sonar.projectKey=server-info
sonar.projectName=server-info
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=test/**,src/public/**
sonar.sourceEncoding=UTF-8
